"""Человеческие названия жанров Флибусты (коды из inp/inpx)."""

# код в каталоге -> как показывать
GENRE_LABELS = {
    "sf": "Научная фантастика",
    "sf_history": "Альтернативная история",
    "sf_action": "Боевая фантастика",
    "sf_epic": "Эпическая фантастика",
    "sf_heroic": "Героическая фантастика",
    "sf_detective": "Детективная фантастика",
    "sf_cyberpunk": "Киберпанк",
    "sf_space": "Космическая фантастика",
    "sf_social": "Социальная фантастика",
    "sf_horror": "Ужасы и мистика",
    "sf_humor": "Юмористическая фантастика",
    "sf_fantasy": "Фэнтези",
    "sf_fantasy_city": "Городское фэнтези",
    "fantasy": "Фэнтези",
    "popadancy": "Попаданцы",
    "child_sf": "Детская фантастика",
    "detective": "Детективы",
    "det_classic": "Классический детектив",
    "det_police": "Полицейский детектив",
    "det_action": "Боевик",
    "det_irony": "Иронический детектив",
    "det_history": "Исторический детектив",
    "det_espionage": "Шпионский детектив",
    "det_crime": "Криминальный детектив",
    "det_political": "Политический детектив",
    "det_maniac": "Маньяки",
    "det_hard": "Крутой детектив",
    "thriller": "Триллеры",
    "love": "Любовные романы",
    "love_contemporary": "Современный любовный роман",
    "love_history": "Исторический любовный роман",
    "love_detective": "Остросюжетный любовный роман",
    "love_short": "Короткий любовный роман",
    "love_sf": "Любовная фантастика",
    "prose": "Проза",
    "prose_classic": "Классическая проза",
    "prose_history": "Историческая проза",
    "prose_contemporary": "Современная проза",
    "prose_counter": "Контркультура",
    "prose_rus_classic": "Русская классика",
    "prose_su_classics": "Советская классика",
    "adventure": "Приключения",
    "adv_western": "Вестерн",
    "adv_history": "Исторические приключения",
    "adv_indian": "Приключения про индейцев",
    "adv_maritime": "Морские приключения",
    "adv_geo": "Путешествия",
    "adv_animal": "Природа и животные",
    "child_adv": "Детские приключения",
    "children": "Детям",
    "child_tale": "Сказки",
    "child_verse": "Детские стихи",
    "child_prose": "Детская проза",
    "child_det": "Детский детектив",
    "child_education": "Детям: учёба",
    "antique": "Старинная литература",
    "antique_ant": "Античная литература",
    "antique_european": "Европейская старинная",
    "antique_russian": "Древнерусская литература",
    "antique_east": "Древневосточная литература",
    "antique_myths": "Мифы и эпос",
    "sci_history": "История",
    "sci_psychology": "Психология",
    "sci_culture": "Культурология",
    "sci_religion": "Религиоведение",
    "sci_philosophy": "Философия",
    "sci_politics": "Политика",
    "sci_business": "Деловая литература",
    "sci_juris": "Юриспруденция",
    "sci_linguistic": "Языкознание",
    "sci_medicine": "Медицина",
    "sci_phys": "Физика",
    "sci_math": "Математика",
    "sci_chem": "Химия",
    "sci_biology": "Биология",
    "sci_tech": "Техника",
    "science": "Наука",
    "sci_popular": "Научпоп",
    "computers": "Компьютеры",
    "comp_www": "Интернет",
    "comp_programming": "Программирование",
    "comp_hard": "Компьютерное железо",
    "comp_soft": "Программы",
    "comp_db": "Базы данных",
    "comp_osnet": "ОС и сети",
    "reference": "Справочники",
    "ref_encyc": "Энциклопедии",
    "ref_dict": "Словари",
    "ref_ref": "Справочная литература",
    "ref_guide": "Руководства",
    "nonfiction": "Документальная литература",
    "nonf_biography": "Биографии и мемуары",
    "nonf_publicism": "Публицистика",
    "nonf_criticism": "Критика",
    "design": "Искусство и дизайн",
    "religion": "Религия",
    "religion_rel": "Религиозная литература",
    "religion_esoterics": "Эзотерика",
    "religion_self": "Самосовершенствование",
    "humor": "Юмор",
    "humor_anecdote": "Анекдоты",
    "humor_prose": "Юмористическая проза",
    "humor_verse": "Юмористические стихи",
    "home": "Дом и семья",
    "home_cooking": "Кулинария",
    "home_pets": "Домашние животные",
    "home_crafts": "Хобби и ремёсла",
    "home_entertain": "Развлечения",
    "home_health": "Здоровье",
    "home_garden": "Сад и огород",
    "home_diy": "Сделай сам",
    "home_sport": "Спорт",
    "home_sex": "Эротика",
    "poetry": "Поэзия",
    "dramaturgy": "Драматургия",
    "banking": "Финансы и банки",
    "economics": "Экономика",
    "economics_ref": "Экономика и бизнес",
    "marketing": "Маркетинг",
    "popular_business": "Бизнес",
    "org_behavior": "Управление и продажи",
    "trade": "Торговля",
    "geo_guides": "Путеводители",
}

# Полки для экрана: одно понятное имя = несколько кодов каталога.
CATALOG_SHELVES = (
    {"id": "s:sf", "group": "Фантастика", "title": "Научная фантастика", "emoji": "🚀", "codes": ("sf", "sf_space", "sf_social", "sf_cyberpunk", "sf_action", "sf_epic", "sf_heroic", "sf_history", "sf_detective", "sf_humor")},
    {"id": "s:fantasy", "group": "Фантастика", "title": "Фэнтези", "emoji": "✨", "codes": ("sf_fantasy", "sf_fantasy_city", "fantasy")},
    {"id": "s:horror", "group": "Фантастика", "title": "Ужасы и мистика", "emoji": "🕯", "codes": ("sf_horror",)},
    {"id": "s:popadancy", "group": "Фантастика", "title": "Попаданцы", "emoji": "⏳", "codes": ("popadancy",)},
    {"id": "s:det", "group": "Детективы", "title": "Детективы", "emoji": "🔍", "codes": ("detective", "det_classic", "det_police", "det_irony", "det_history", "det_espionage", "det_crime", "det_political", "det_hard")},
    {"id": "s:action", "group": "Детективы", "title": "Боевики", "emoji": "💥", "codes": ("det_action",)},
    {"id": "s:thriller", "group": "Детективы", "title": "Триллеры", "emoji": "⚡", "codes": ("thriller", "det_maniac")},
    {"id": "s:love", "group": "Любовные романы", "title": "Любовные романы", "emoji": "💕", "codes": ("love", "love_contemporary", "love_history", "love_detective", "love_short", "love_sf")},
    {"id": "s:prose_now", "group": "Проза", "title": "Современная проза", "emoji": "📖", "codes": ("prose_contemporary", "prose", "prose_counter")},
    {"id": "s:prose_classic", "group": "Проза", "title": "Классика", "emoji": "📜", "codes": ("prose_classic", "prose_rus_classic", "prose_su_classics")},
    {"id": "s:prose_hist", "group": "Проза", "title": "Историческая проза", "emoji": "🏛", "codes": ("prose_history",)},
    {"id": "s:adv", "group": "Приключения", "title": "Приключения", "emoji": "🧭", "codes": ("adventure", "adv_history", "adv_maritime", "adv_western", "adv_indian", "adv_geo", "adv_animal")},
    {"id": "s:kids", "group": "Детям", "title": "Детям", "emoji": "🧸", "codes": ("children", "child_tale", "child_prose", "child_verse", "child_adv", "child_sf", "child_det", "child_education")},
    {"id": "s:poetry", "group": "Поэзия и театр", "title": "Поэзия", "emoji": "✒️", "codes": ("poetry",)},
    {"id": "s:drama", "group": "Поэзия и театр", "title": "Пьесы", "emoji": "🎭", "codes": ("dramaturgy",)},
    {"id": "s:humor", "group": "Юмор", "title": "Юмор", "emoji": "😄", "codes": ("humor", "humor_prose", "humor_verse", "humor_anecdote", "sf_humor")},
    {"id": "s:psych", "group": "Психология и развитие", "title": "Психология", "emoji": "🧠", "codes": ("sci_psychology",), "needles": ("психолог", "психотерап")},
    {"id": "s:self", "group": "Психология и развитие", "title": "Саморазвитие", "emoji": "🌱", "codes": ("religion_self",), "needles": ("саморазвит", "мотивац", "привычк")},
    {"id": "s:sales", "group": "Деловое", "title": "Продажи и маркетинг", "emoji": "💬", "codes": ("marketing", "trade", "popular_business", "org_behavior", "economics_ref"), "needles": ("продаж", "маркетинг", "сбыт", "ритейл", "переговор")},
    {"id": "s:business", "group": "Деловое", "title": "Бизнес", "emoji": "💼", "codes": ("sci_business", "banking", "economics"), "needles": ("бизнес", "управлен", "менеджмент", "предпринимат")},
    {"id": "s:history", "group": "Документальное", "title": "История", "emoji": "🏛", "codes": ("sci_history",)},
    {"id": "s:bio", "group": "Документальное", "title": "Биографии", "emoji": "👤", "codes": ("nonf_biography",)},
    {"id": "s:publicism", "group": "Документальное", "title": "Публицистика", "emoji": "📰", "codes": ("nonf_publicism", "nonf_criticism", "nonfiction")},
    {"id": "s:science", "group": "Наука", "title": "Наука и техника", "emoji": "🔬", "codes": ("science", "sci_popular", "sci_phys", "sci_math", "sci_chem", "sci_biology", "sci_tech", "sci_medicine")},
    {"id": "s:comp", "group": "Наука", "title": "Компьютеры", "emoji": "💻", "codes": ("computers", "comp_www", "comp_programming", "comp_hard", "comp_soft", "comp_db", "comp_osnet")},
    {"id": "s:home", "group": "Дом и досуг", "title": "Дом, сад, здоровье", "emoji": "🏡", "codes": ("home", "home_cooking", "home_pets", "home_crafts", "home_health", "home_garden", "home_diy", "home_sport", "home_entertain")},
    {"id": "s:religion", "group": "Дом и досуг", "title": "Религия и эзотерика", "emoji": "🕯", "codes": ("religion", "religion_rel", "religion_esoterics", "sci_religion")},
    {"id": "s:antique", "group": "Старинное", "title": "Мифы и древность", "emoji": "🏺", "codes": ("antique", "antique_ant", "antique_european", "antique_russian", "antique_east", "antique_myths")},
)


def normalize_genre_code(raw: str) -> str:
    t = (raw or "").strip().strip(":").lower().replace(" ", "_")
    return t
